Первый коммит спиринта
utopya88/java-kanban pull request #1
Opened 2024-04-15 21:27 UTC by utopya88

Сделал основную задачу. Жду комментариев

2024-04-16 22:28 UTC, mikita95 requested changes
Все отлично :) Оставил лишь небольшие замечания. Также папку .idea не нужно выгружать в репозиторий, лучше добавить ее в gitignore

2024-04-16 22:28 UTC, mikita95 commented on src/model/CustomLinkedList.java
> +
Лишние переносы в конце файла

2024-04-16 22:28 UTC, mikita95 commented on src/model/CustomLinkedList.java
> +    public Map<Integer, Node> getHistory() {
Лучше просто возвращать список задач наружу, иначе сейчас происходит нарушение инкапсуляции, так как возвращается внутренняя реализация

2024-04-18 11:06 UTC, utopya88 commented
сделал изменения.жду оценки

2024-04-19 09:40 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-09-02 20:38 UTC, closed without merging